-- AlterTable
ALTER TABLE `beasts` MODIFY `rarity` ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'MYTHIC', 'ASCENDED') NOT NULL;

-- AlterTable
ALTER TABLE `equipment` MODIFY `rarity` ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'MYTHIC', 'ASCENDED') NOT NULL;

-- AlterTable
ALTER TABLE `items` MODIFY `rarity` ENUM('COMMON', 'UNCOMMON', 'RARE', 'LEGENDARY', 'MYTHIC', 'ASCENDED') NOT NULL;
